// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuI7A9DYFid57zaJ1YyJveTpb7BEYr4Vo',
    appId: '1:304558346701:android:0806e298127f352be87484',
    messagingSenderId: '304558346701',
    projectId: 'flutter-rpg-96295',
    storageBucket: 'flutter-rpg-96295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuT9wUJnkqNqBOObkSK9HN_zStfBymrm4',
    appId: '1:304558346701:ios:f36db8b8ac3c07b3e87484',
    messagingSenderId: '304558346701',
    projectId: 'flutter-rpg-96295',
    storageBucket: 'flutter-rpg-96295.firebasestorage.app',
    iosBundleId: 'com.example.rpg',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRkiMvs4No7ZORpbUmV6yP_S0Cy5F919c',
    appId: '1:304558346701:web:5ae1432e1fc0e9dbe87484',
    messagingSenderId: '304558346701',
    projectId: 'flutter-rpg-96295',
    authDomain: 'flutter-rpg-96295.firebaseapp.com',
    storageBucket: 'flutter-rpg-96295.firebasestorage.app',
  );

}